# action.yml
name: 'PM Docker Builder'
description: 'Build and push docker images easly'
author: 'Aram Kocharyan '
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'aperture'
  color: 'blue'
